# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: hana

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'olklause internal Azure Subscription(7731e98e-6e6d-42e8-9ba9-647c11b6fce1)'
    subscriptionId: '7731e98e-6e6d-42e8-9ba9-647c11b6fce1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'MySAPAutomation_RG'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/oklausen/sap-hana-vm/main/azuredeploy.json'
    csmParametersFileLink: 'https://filestorageokl.blob.core.windows.net/deploymentparameter/parametersFile.json'
    deploymentMode: 'Complete'

